#!/bin/bash
# merge.sh — Downloads all filter lists, deduplicates, and merges into a single file.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
SOURCES="$REPO_DIR/sources.txt"
CUSTOM="$REPO_DIR/custom-rules.txt"
OUTPUT="$REPO_DIR/filters.txt"
TEMP_DIR=$(mktemp -d)

trap 'rm -rf "$TEMP_DIR"' EXIT

echo ">> Downloading filter lists..."

total=0
success=0
failed=0

while IFS= read -r url; do
    # Skip comments and blank lines
    [[ -z "$url" || "$url" =~ ^# ]] && continue

    total=$((total + 1))
    filename="$TEMP_DIR/list_${total}.txt"

    if curl -s -L --max-time 120 --retry 2 --retry-delay 5 -o "$filename" "$url" 2>/dev/null; then
        lines=$(wc -l < "$filename" | tr -d ' ')
        echo "   [OK] $lines lines — ${url:0:80}"
        success=$((success + 1))
    else
        echo "   [FAIL] $url"
        rm -f "$filename"
        failed=$((failed + 1))
    fi
done < "$SOURCES"

echo ""
echo ">> Downloaded $success/$total lists ($failed failed)"
echo ">> Processing rules..."

# Extract non-comment, non-blank, non-header lines from all downloaded lists
# Keep lines that are actual filter rules
cat "$TEMP_DIR"/list_*.txt 2>/dev/null \
    | grep -v '^\s*$' \
    | grep -v '^!' \
    | grep -v '^\[Adblock' \
    | grep -v '^# ' \
    | grep -v '^#$' \
    > "$TEMP_DIR/all_rules_raw.txt"

echo "   Raw rules: $(wc -l < "$TEMP_DIR/all_rules_raw.txt" | tr -d ' ')"

# Deduplicate (sort -u)
sort -u "$TEMP_DIR/all_rules_raw.txt" > "$TEMP_DIR/all_rules_dedup.txt"
echo "   After dedup: $(wc -l < "$TEMP_DIR/all_rules_dedup.txt" | tr -d ' ')"

# Extract custom rules (keep comments for section readability)
grep -v '^\s*$' "$CUSTOM" > "$TEMP_DIR/custom_rules.txt" 2>/dev/null || true

# Count totals
subscription_count=$(wc -l < "$TEMP_DIR/all_rules_dedup.txt" | tr -d ' ')
custom_count=$(grep -cv '^!' "$TEMP_DIR/custom_rules.txt" 2>/dev/null | tr -d ' ' || echo "0")
total_rules=$((subscription_count + custom_count))

# Generate timestamp
timestamp=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

# Build the final file
cat > "$OUTPUT" << HEADER
! Title: Samir's Ultimate Filter List
! Description: Comprehensive ad, tracker, malware, phishing & annoyance protection
! Last updated: ${timestamp}
! Expires: 1 day
! Homepage: https://github.com/SamirPaulb/filter-lists
! License: https://github.com/SamirPaulb/filter-lists/blob/main/LICENSE
! Total rules: ${total_rules} (${subscription_count} from ${success} sources + ${custom_count} custom)
!
! Auto-generated by GitHub Actions. Do not edit directly.
! To modify: edit sources.txt or custom-rules.txt and push.
!
! SETUP: Subscribe to this single URL in your browser:
!   https://raw.githubusercontent.com/SamirPaulb/filter-lists/main/filters.txt
!
! ==============================
! SUBSCRIPTION RULES (merged from ${success} sources)
! ==============================
HEADER

cat "$TEMP_DIR/all_rules_dedup.txt" >> "$OUTPUT"

cat >> "$OUTPUT" << SEPARATOR

! ==============================
! CUSTOM RULES
! ==============================
SEPARATOR

cat "$TEMP_DIR/custom_rules.txt" >> "$OUTPUT"

echo ""
echo ">> Output: $OUTPUT"
echo ">> Total rules: $total_rules ($subscription_count subscription + $custom_count custom)"
echo ">> Done!"

